// <auto-generated />
using System;
using Deals.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Deals.Infrastructure.Migrations
{
    [DbContext(typeof(DealsDbContext))]
    [Migration("20260126051006_AddDealPayments")]
    partial class AddDealPayments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Deals.Entities.Deals.Deal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdvertiserUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("advertiser_user_id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<DateTimeOffset>("DesiredPublishAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("desired_publish_at_utc");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("PaymentState")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_state");

                    b.Property<string>("PostText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("post_text");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AdvertiserUserId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DealId")
                        .IsUnique();

                    b.HasIndex("PublisherUserId");

                    b.ToTable("deals", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
