// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Payments.Infrastructure.Persistence;

#nullable disable

namespace Payments.Infrastructure.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Payments.Entities.PublisherLedger.PublisherLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<decimal>("GrossAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("platform_fee_amount");

                    b.Property<decimal>("PublisherAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("publisher_amount");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .IsUnique();

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.HasIndex("PublisherUserId");

                    b.HasIndex("Status");

                    b.ToTable("publisher_ledger_entries", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.PublisherLedger.PublisherWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Available")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("PaidOut")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("paid_out");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("PublisherUserId")
                        .IsUnique();

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("publisher_wallets", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.PublisherLedger.PublisherWithdrawal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("DestinationCardMask")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("destination_card_mask");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<Guid>("WithdrawalId")
                        .HasColumnType("uuid")
                        .HasColumnName("withdrawal_id");

                    b.HasKey("Id");

                    b.HasIndex("PublisherUserId");

                    b.HasIndex("WithdrawalId")
                        .IsUnique();

                    b.ToTable("publisher_withdrawals", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.TopUps.TopUp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("ConfirmationUrl")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TopUpId")
                        .HasColumnType("uuid")
                        .HasColumnName("topup_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("TopUpId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("YooKassaPaymentId")
                        .IsUnique();

                    b.ToTable("topups", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.Wallet.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DealId")
                        .IsUnique();

                    b.HasIndex("PublisherUserId");

                    b.HasIndex("ReservationId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.Wallet.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Available")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("available");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Reserved")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("reserved");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("WalletId")
                        .IsUnique();

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.Wallet.WalletTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DealId")
                        .HasColumnType("uuid")
                        .HasColumnName("deal_id");

                    b.Property<Guid?>("TopUpId")
                        .HasColumnType("uuid")
                        .HasColumnName("topup_id");

                    b.Property<Guid>("TxId")
                        .HasColumnType("uuid")
                        .HasColumnName("tx_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("TopUpId");

                    b.HasIndex("TxId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("wallet_transactions", (string)null);
                });

            modelBuilder.Entity("Payments.Entities.Webhooks.YooKassaWebhookInboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("remote_ip");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("yookassa_payment_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("ProcessedAt");

                    b.ToTable("yookassa_webhook_inbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
