// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Publishers.Infrastructure.Persistence;

#nullable disable

namespace Publishers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PublishersDbContext))]
    [Migration("20260125065458_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Publishers.Entities.Channels.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IntakeMode")
                        .HasColumnType("integer")
                        .HasColumnName("intake_mode");

                    b.Property<int>("OwnershipStatus")
                        .HasColumnType("integer")
                        .HasColumnName("ownership_status");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_user_id");

                    b.Property<string>("TelegramChannelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("telegram_channel_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("verification_code");

                    b.Property<DateTimeOffset?>("VerificationExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verification_expires_at");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.HasIndex("PublisherUserId", "TelegramChannelId")
                        .IsUnique();

                    b.ToTable("channels", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
